### ISSUE TITLE
Use @supports to hint compatibility

### ISSUE THREAD

**Issue by Manishearth** [lukehaas/css-pokemon#1]
Do something like

```css
@supports(not clip-path: polygon(..)) {
    #nosupport {display: block}
}
```

and then have a div with `id=nosupport` that mentions. "`clip-path` is not supported in the browser that you're currently using. If on Firefox, go to `about:config` and enable `layout.css.clip-path-shapes.enabled` to view".

This reduces confusion.
